name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make nix
      run: make nix
    - name: mkn
      run: KLOG=3 ./mkn clean build test -tKOW 9 -g 0 -p @,test -w mkn.ram[https]
    - uses: actions/upload-artifact@v1
      with:
        name: mkn
        path: mkn
