name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: make nix

    - run: KLOG=3 ./mkn build -dtKOW 9 -g 0 -w mkn.ram[https] -a "-std=c++17 -fPIC"

    - uses: actions/upload-artifact@v1
      with:
        name: mkn
        path: bin/build/mkn
