name: ubuntu-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: make nix

    - env:
        MKN_GCC_PREFERRED: 1
        KUL_GIT_CO: --depth 1
      run: KLOG=3 ./mkn build -dtKa "-std=c++17 -fPIC" -O 2 -g 0 -W 9

    - uses: actions/upload-artifact@v1
      with:
        name: mkn
        path: bin/build/mkn
