name: ubuntu-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: allenevans/set-env@v1.0.0
      with:
        KUL_GIT_CO: --depth 10 # is added to git clone calls

    - run: make nix

    - run: KLOG=3 ./mkn build -dtKa "-std=c++17 -fPIC" -O 2 -g 0 -W 9

    - uses: actions/upload-artifact@v1
      with:
        name: mkn
        path: bin/build/mkn
